"""add motivation and referrer

Revision ID: 00dfe65d6f96
Revises: adf66e7e9041
Create Date: 2025-06-20 03:09:01.930552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00dfe65d6f96'
down_revision: Union[str, Sequence[str], None] = 'adf66e7e9041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivation_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motivation_phrases_id'), 'motivation_phrases', ['id'], unique=False)
    op.add_column('users', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_referrer_id'), 'users', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referrer_id'), table_name='users')
    op.drop_column('users', 'referrer_id')
    op.drop_index(op.f('ix_motivation_phrases_id'), table_name='motivation_phrases')
    op.drop_table('motivation_phrases')
    # ### end Alembic commands ###
