"""initial

Revision ID: 764d624ab69b
Revises: 
Create Date: 2025-06-19 20:34:37.309653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764d624ab69b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.String(), nullable=True),
    sa.Column('share', sa.Integer(), nullable=True),
    sa.Column('invited', sa.Integer(), nullable=True),
    sa.Column('payments_sum', sa.Integer(), nullable=True),
    sa.Column('earned', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('referral_link', sa.String(), nullable=True),
    sa.Column('materials_link', sa.String(), nullable=True),
    sa.Column('withdraw_requested', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliates_id'), 'affiliates', ['id'], unique=False)
    op.create_index(op.f('ix_affiliates_user_id'), 'affiliates', ['user_id'], unique=False)
    op.create_table('favorite_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_suppliers_id'), 'favorite_suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_suppliers_supplier_id'), 'favorite_suppliers', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_favorite_suppliers_user_id'), 'favorite_suppliers', ['user_id'], unique=False)
    op.create_table('finds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finds_id'), 'finds', ['id'], unique=False)
    op.create_index(op.f('ix_finds_supplier_id'), 'finds', ['supplier_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('category1', sa.String(), nullable=True),
    sa.Column('category2', sa.String(), nullable=True),
    sa.Column('contact_link', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('contact_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_number', sa.String(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_agent_number'), 'users', ['agent_number'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_agent_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_finds_supplier_id'), table_name='finds')
    op.drop_index(op.f('ix_finds_id'), table_name='finds')
    op.drop_table('finds')
    op.drop_index(op.f('ix_favorite_suppliers_user_id'), table_name='favorite_suppliers')
    op.drop_index(op.f('ix_favorite_suppliers_supplier_id'), table_name='favorite_suppliers')
    op.drop_index(op.f('ix_favorite_suppliers_id'), table_name='favorite_suppliers')
    op.drop_table('favorite_suppliers')
    op.drop_index(op.f('ix_affiliates_user_id'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_id'), table_name='affiliates')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
