name: Fully Automerge Codex PRs

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash       # <--- ВАЖНО: только через env!
          MERGE_LABELS: codex        # <--- тоже через env!
