name: Auto-merge Codex PRs

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          merge-method: squash
