name: Auto-merge Codex PRs

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash   # Можно заменить на 'merge' или 'rebase', если нужно

      - name: Merge pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (pr.auto_merge) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: "squash"
              });
            }
