name: Fully Automerge Codex PRs

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review]
  check_suite:
    types: [completed]

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'codex')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Automerge PR
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          merge_method: squash
          labels: codex
